package aggregation.ex3;

public enum DistrictEnum {
	BREST_DISTRICT, BARANAVICHY_DISTRICT, PINSK_DISTRICT, KOBRYN_DISTRICT, 
    BYAROZA_DISTRICT, IVATSEVICHY_DISTRICT, LUNINYETS_DISTRICT, PRUZHANY_DISTRICT, 
    IVANAVA_DISTRICT, DRAHICHYN_DISTRICT, HANTSAVICHY_DISTRICT,ZHABINKA_DISTRICT,
    STOLIN_DISTRICT, LYAKHAVICHY_DISTRICT, MALARYTA_DISTRICT, KAMYANYETS_DISTRICT,
    VYSOKAYE_DISTRICT, 

    VITEBSK_DISTRICT, ORSHA_DISTRICT, POLOTSK_DISTRICT, PASTAVY_DISTRICT,
    HLYBOKAYE_DISTRICT, LEPEL_DISTRICT, HARADOK_DISTRICT, TALACYN_DISTRICT,
    BRASLAU_DISTRICT, CASNIKI_DISTRICT, DUBROUNA_DISTRICT, MIORY_DISTRICT, 
    SYANNO_DISTRICT, BESHANKOVICHY_DISTRICT, VERKHNYADZVINSK_DISTRICT,
    DOKSHYTSY_DISTRICT, USHACHYU_DISTRICT,

    GOMEL_DISTRICT, MAZYR_DISTRICT, ZHLOBIN_DISTRICT, SVIETLAHORSK_DISTRICT, 
    RECHYTSA_DISTRICT, KALINKAVICHY_DISTRICT, RAHACHOW_DISTRICT, DOBRUSH_DISTRICT, 
    ZHYTKAVICHY_DISTRICT, KHOYNIKI_DISTRICT, PIETRYKAW_DISTRICT, YEL_SK_DISTRICT, 
    BUDA_KASHALYOVA_DISTRICT, NAROULIA_DISTRICT, VIETKA_DISTRICT, CHACHERSK_DISTRICT,
    BRAHIN_DISTRICT, 

    GRODNO_DISTRICT, LIDA_DISTRICT, SLONIM_DISTRICT, VAWKAVYSK_DISTRICT, 
    SMARHON_DISTRICT, NAVAHRUDAK_DISTRICT, ASHMYANY_DISTRICT, MASTY_DISTRICT, 
    SHCHUCHYN_DISTRICT, ASTRAVYETS_DISTRICT, 
    IWYE_DISTRICT, DZIATLAVA_DISTRICT, ZELVA_DISTRICT, 
    KARELICHY_DISTRICT, SVISLACH_DISTRICT, VORANAVA_DISTRICT, VYALIKAYA_BYERASTAVITSA_DISTRICT, 

    BARYSAW_DISTRICT, SALIHORSK_DISTRICT, MALADZYECHNA_DISTRICT, SLUTSK_DISTRICT, 
    VILEYKA_DISTRICT, DZYARZHYNSK_DISTRICT, MARYINA_HORKA_DISTRICT, 
    STOWBTSY_DISTRICT, SMALYAVICHY_DISTRICT, LYUBAN_DISTRICT, STARYYA_DAROHI_DISTRICT, 
    VALOZHYN_DISTRICT, LAHOYSK_DISTRICT, KAPYL_DISTRICT, KLETSK_DISTRICT, 
    CHERVYEN_DISTRICT, UZDA_DISTRICT, KRUPKI_DISTRICT, MYADZYEL_DISTRICT, MINSK_DISTRICT,

    MOGILEV_DISTRICT, BABRUYSK_DISTRICT, ASIPOVICHY_DISTRICT, HORKI_DISTRICT, 
    KRYCHAW_DISTRICT, BYKHAW_DISTRICT, KASTSYUKOVICHY_DISTRICT, 
    KLIMAVICHY_DISTRICT, SHKLOW_DISTRICT, MSTSISLAW_DISTRICT, CHAVUSY_DISTRICT, 
    CHERYKAW_DISTRICT, SLAWHARAD_DISTRICT, KLICHAW_DISTRICT;
	
	public RegionEnum getRegionEnum() {
        switch (this) {
            case BREST_DISTRICT:
            case BARANAVICHY_DISTRICT:
            case PINSK_DISTRICT:
            case KOBRYN_DISTRICT:
            case BYAROZA_DISTRICT:
            case IVATSEVICHY_DISTRICT:
            case LUNINYETS_DISTRICT:
            case PRUZHANY_DISTRICT:
            case IVANAVA_DISTRICT:
            case DRAHICHYN_DISTRICT:
            case HANTSAVICHY_DISTRICT:
            case ZHABINKA_DISTRICT:
            case STOLIN_DISTRICT:
            case LYAKHAVICHY_DISTRICT:
            case MALARYTA_DISTRICT:
            case KAMYANYETS_DISTRICT:
            case VYSOKAYE_DISTRICT:
                return RegionEnum.BREST_REGION;

            case VITEBSK_DISTRICT:
            case ORSHA_DISTRICT:
            case POLOTSK_DISTRICT:
            case PASTAVY_DISTRICT:
            case HLYBOKAYE_DISTRICT:
            case LEPEL_DISTRICT:
            case HARADOK_DISTRICT:
            case TALACYN_DISTRICT:
            case BRASLAU_DISTRICT:
            case CASNIKI_DISTRICT:
            case DUBROUNA_DISTRICT:
            case MIORY_DISTRICT:
            case SYANNO_DISTRICT:
            case BESHANKOVICHY_DISTRICT:
            case VERKHNYADZVINSK_DISTRICT:
            case DOKSHYTSY_DISTRICT:
            case USHACHYU_DISTRICT:
                return RegionEnum.VITEBSK_REGION;

            case GOMEL_DISTRICT:
            case MAZYR_DISTRICT:
            case ZHLOBIN_DISTRICT:
            case SVIETLAHORSK_DISTRICT:
            case RECHYTSA_DISTRICT:
            case KALINKAVICHY_DISTRICT:
            case RAHACHOW_DISTRICT:
            case DOBRUSH_DISTRICT:
            case ZHYTKAVICHY_DISTRICT:
            case KHOYNIKI_DISTRICT:
            case PIETRYKAW_DISTRICT:
            case YEL_SK_DISTRICT:
            case BUDA_KASHALYOVA_DISTRICT:
            case NAROULIA_DISTRICT:
            case VIETKA_DISTRICT:
            case CHACHERSK_DISTRICT:
            case BRAHIN_DISTRICT:
                return RegionEnum.GOMEL_REGION;

            case GRODNO_DISTRICT:
            case LIDA_DISTRICT:
            case SLONIM_DISTRICT:
            case VAWKAVYSK_DISTRICT:
            case SMARHON_DISTRICT:
            case NAVAHRUDAK_DISTRICT:
            case ASHMYANY_DISTRICT:
            case MASTY_DISTRICT:
            case SHCHUCHYN_DISTRICT:
            case ASTRAVYETS_DISTRICT:
            case IWYE_DISTRICT:
            case DZIATLAVA_DISTRICT:
            case ZELVA_DISTRICT:
            case KARELICHY_DISTRICT:
            case SVISLACH_DISTRICT:	
            case VORANAVA_DISTRICT:	
            case VYALIKAYA_BYERASTAVITSA_DISTRICT:
                return RegionEnum.GRODNO_REGION;

            case BARYSAW_DISTRICT:
            case SALIHORSK_DISTRICT:
            case MALADZYECHNA_DISTRICT:
            case SLUTSK_DISTRICT:
            case SMALYAVICHY_DISTRICT:
            case VILEYKA_DISTRICT:
            case DZYARZHYNSK_DISTRICT:
            case MARYINA_HORKA_DISTRICT:
            case STOWBTSY_DISTRICT:
            case LYUBAN_DISTRICT:
            case STARYYA_DAROHI_DISTRICT:
            case VALOZHYN_DISTRICT:
            case LAHOYSK_DISTRICT:
            case KAPYL_DISTRICT:
            case KLETSK_DISTRICT:
            case CHERVYEN_DISTRICT:
            case UZDA_DISTRICT:
            case KRUPKI_DISTRICT:
            case MYADZYEL_DISTRICT:
            case MINSK_DISTRICT:
                return RegionEnum.MINSK_REGION;

            case MOGILEV_DISTRICT:
            case BABRUYSK_DISTRICT:
            case ASIPOVICHY_DISTRICT:
            case HORKI_DISTRICT:
            case KRYCHAW_DISTRICT:
            case BYKHAW_DISTRICT:
            case KASTSYUKOVICHY_DISTRICT:
            case KLIMAVICHY_DISTRICT:
            case SHKLOW_DISTRICT:
            case MSTSISLAW_DISTRICT:
            case CHAVUSY_DISTRICT:
            case CHERYKAW_DISTRICT:
            case SLAWHARAD_DISTRICT:
            case KLICHAW_DISTRICT:
                return RegionEnum.MOGILEV_REGION;

            default:
                throw new IllegalArgumentException("Unexpected value: " + this);
        }
	}

}
